package enums;

public enum COUNTRIES {

 UNITED_STATES, CANADA, MEXICO, BELICE, COSTA_RICA, EL_SALVADOR, GUATEMALA, HONDURAS, NICARAGUA, PANAMA, ARGENTINA, BOLIVIA, BRASIL, CHILE, COLOMBIA, ECUADOR, PARAGUAY, SURINAM, PERU, TRINIDAD_Y_TOBAGO, URUGUAY, VENEZUELA, ANTIGUA_Y_BARBUDA, BAHAMAS, BARBADOS, CUBA, DOMINICA, GRANADA, GUYANA, HAITI, JAMAICA, REPUBLICA_DOMINICANA, SAN_CRISTOBAL_Y_NIEVES, SAN_VICENTE_Y_LAS_GRANADINAS, SANTA_LUCIA, PUERTO_RICO;
}
