package controller;

import javafx.fxml.FXML;
import application.Main;
import javafx.event.ActionEvent;
import javafx.scene.control.Button;
import javafx.scene.control.Menu;

public class MenuController
{
	private Main main;
	
	@FXML
	private Button addButton;

	@FXML
	public void addPeople() {
		main.showAddPeople();
	}
	
	@FXML
	public void close() {
		// TODO Autogenerated
	}
	
	@FXML
	public void searchByName() {
		main.searchByName();
	}

	@FXML
	public void searchByLastName() {
		main.searchByLastName();
	}

	@FXML
	public void searchByFullName() {
		main.searchByFullName();
	}
	
	@FXML
	public void searchByCode() {
		main.searchByCode();
	}
	public Main getMain() {
		return main;
	}
	public void setMain(Main main) {
		this.main = main;
	}
}
